--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Actor; Type: TABLE; Schema: public; Owner: helen
--

CREATE TABLE public."Actor" (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer,
    gender character varying(50)
);


ALTER TABLE public."Actor" OWNER TO helen;

--
-- Name: Actor_id_seq; Type: SEQUENCE; Schema: public; Owner: helen
--

CREATE SEQUENCE public."Actor_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Actor_id_seq" OWNER TO helen;

--
-- Name: Actor_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: helen
--

ALTER SEQUENCE public."Actor_id_seq" OWNED BY public."Actor".id;


--
-- Name: Movie; Type: TABLE; Schema: public; Owner: helen
--

CREATE TABLE public."Movie" (
    id integer NOT NULL,
    title character varying NOT NULL,
    release_date date
);


ALTER TABLE public."Movie" OWNER TO helen;

--
-- Name: Movie_id_seq; Type: SEQUENCE; Schema: public; Owner: helen
--

CREATE SEQUENCE public."Movie_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Movie_id_seq" OWNER TO helen;

--
-- Name: Movie_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: helen
--

ALTER SEQUENCE public."Movie_id_seq" OWNED BY public."Movie".id;


--
-- Name: actor_movie; Type: TABLE; Schema: public; Owner: helen
--

CREATE TABLE public.actor_movie (
    actor_id integer NOT NULL,
    movie_id integer NOT NULL
);


ALTER TABLE public.actor_movie OWNER TO helen;

--
-- Name: Actor id; Type: DEFAULT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public."Actor" ALTER COLUMN id SET DEFAULT nextval('public."Actor_id_seq"'::regclass);


--
-- Name: Movie id; Type: DEFAULT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public."Movie" ALTER COLUMN id SET DEFAULT nextval('public."Movie_id_seq"'::regclass);


--
-- Data for Name: Actor; Type: TABLE DATA; Schema: public; Owner: helen
--

COPY public."Actor" (id, name, age, gender) FROM stdin;
2	Jerry	13	male
1	Tom	13	male
5	Alen	32	male
6	Alex	40	male
\.


--
-- Data for Name: Movie; Type: TABLE DATA; Schema: public; Owner: helen
--

COPY public."Movie" (id, title, release_date) FROM stdin;
1	Father Brown	2019-03-02
2	Counterpart	2017-08-02
3	Star Wars 1	1977-01-02
\.


--
-- Data for Name: actor_movie; Type: TABLE DATA; Schema: public; Owner: helen
--

COPY public.actor_movie (actor_id, movie_id) FROM stdin;
1	1
5	2
6	3
\.


--
-- Name: Actor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helen
--

SELECT pg_catalog.setval('public."Actor_id_seq"', 6, true);


--
-- Name: Movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: helen
--

SELECT pg_catalog.setval('public."Movie_id_seq"', 3, true);


--
-- Name: Actor Actor_pkey; Type: CONSTRAINT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public."Actor"
    ADD CONSTRAINT "Actor_pkey" PRIMARY KEY (id);


--
-- Name: Movie Movie_pkey; Type: CONSTRAINT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public."Movie"
    ADD CONSTRAINT "Movie_pkey" PRIMARY KEY (id);


--
-- Name: actor_movie actor_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_pkey PRIMARY KEY (actor_id, movie_id);


--
-- Name: actor_movie actor_movie_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public."Actor"(id);


--
-- Name: actor_movie actor_movie_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: helen
--

ALTER TABLE ONLY public.actor_movie
    ADD CONSTRAINT actor_movie_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public."Movie"(id);


--
-- PostgreSQL database dump complete
--

